import type { Metadata } from "next";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from "./component/navbar";  
import Intro from "./component/intro";
import About from "./component/about";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="id">
      <body style={{ backgroundColor: "#E7E7E0"}}>
        <Navbar />
        <Intro />
        <About />
        <main>{children}</main>
      </body>
    </html>
  );
}
