import type { Metadata } from "next";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from "./component/navbar";  


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="id">
      <body style={{ backgroundImage: "url('/grey2.jpeg')", backgroundSize: "cover" }}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
